channels:
- conda-forge
dependencies:
- python=3.13.0
- pip<=25.2
- pip:
  - mlflow==3.8.0
  - cloudpickle==3.1.2
  - numpy==2.1.2
  - pandas==2.2.3
  - psutil==6.0.0
  - pyarrow==22.0.0
  - scikit-learn==1.7.2
  - scipy==1.14.1
name: mlflow-env
